apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /polls
            pathType: Prefix
            backend:
              service:
                name: poll-service
                port:
                  name: "poll-port"
          - path: /votes
            pathType: Prefix
            backend:
              service:
                name: vote-service
                port:
                  name: "vote-port"
