apiVersion: v1
kind: Secret
metadata:
  name: postgre-db-secret
type: Opaque
data:
  DbConnection: SG9zdD1kYXRhYmFzZTtQb3J0PTU0MzI7VXNlciBJZD1wb3N0Z3JlcztEYXRhYmFzZT1zZXJ2aWNlO1Bhc3N3b3JkPTFxMnczZTRyOw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vote-service
  name: vote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote-service
  template:
    metadata:
      labels:
        io.kompose.service: vote-service
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__VoteDbConnection
              valueFrom:
                secretKeyRef:
                  name: postgre-db-secret
                  key: DbConnection
          image: ostepanyk/vote_service
          name: vote-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
